# Generated by Django 5.2.4 on 2025-08-13 08:56

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0002_alter_diagnostictest_sample_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diagnostictest",
            name="sample_type",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("Blood", " Blood"),
                    ("Urine", " Urine"),
                    ("Saliva", " Saliva"),
                    ("Stool", " Stool (Feces)"),
                    ("Sputum", " Sputum (Mucus from lungs)"),
                    ("Tissue", " Tissue / Biopsy"),
                    ("Sweat", " Sweat"),
                    ("Cerebrospinal Fluid", " Cerebrospinal Fluid (CSF)"),
                    ("Amniotic Fluid", " Amniotic Fluid"),
                    ("Semen", " Semen"),
                    ("Nasal / Throat Swab", " Nasal / Throat Swab"),
                    ("Hair / Nail", " Hair / Nail"),
                    ("Not Specified", " Not Specified"),
                ],
                max_length=131,
            ),
        ),
    ]
