# Generated by Django 5.2.4 on 2025-08-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0003_alter_diagnostictest_sample_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bloodbank",
            name="affiliated_hospitals",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="bloodbank",
            name="certifications",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="bloodbank",
            name="special_instructions",
            field=models.TextField(
                blank=True, null=True, verbose_name="Special Instructions/Notes"
            ),
        ),
        migrations.AlterField(
            model_name="bloodrequest",
            name="medical_reason",
            field=models.CharField(max_length=255, verbose_name="Medical Reason"),
        ),
        migrations.AlterField(
            model_name="bloodrequest",
            name="notes",
            field=models.TextField(
                blank=True, null=True, verbose_name="Additional Notes"
            ),
        ),
        migrations.AlterField(
            model_name="diagnostictest",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="diagnostictest",
            name="parameters_included",
            field=models.TextField(blank=True, null=True),
        ),
    ]
