# Generated by Django 5.2.4 on 2025-08-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0004_alter_bloodbank_affiliated_hospitals_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointment",
            old_name="zoom_link",
            new_name="video_link",
        ),
        migrations.AddField(
            model_name="appointment",
            name="video_platform",
            field=models.CharField(
                choices=[("jitsi", "Jitsi"), ("zoom", "Zoom")],
                default="jitsi",
                max_length=20,
            ),
        ),
    ]
