# Generated by Django 5.2.9 on 2025-12-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0005_rename_zoom_link_appointment_video_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="blockchain_status",
            field=models.CharField(default="pending", max_length=20),
        ),
        migrations.AddField(
            model_name="appointment",
            name="blockchain_tx_hash",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
