# Generated by Django 5.2.9 on 2025-12-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0006_appointment_blockchain_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Booked", "Booked"),
                    ("Cancelled", "Cancelled"),
                    ("Completed", "Completed"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="lab_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Booked", "Booked"),
                    ("Cancelled", "Cancelled"),
                    ("Completed", "Completed"),
                ],
                default="Booked",
                max_length=50,
            ),
        ),
    ]
