# Generated by Django 5.2.5 on 2025-12-22 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0007_booking_status_alter_booking_lab_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="crypto_amount",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="tx_hash",
            field=models.CharField(blank=True, max_length=66, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="lab_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Booked", "Booked"),
                    ("Cancelled", "Cancelled"),
                    ("Completed", "Completed"),
                    ("Refunded", "Refunded"),
                ],
                default="Booked",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Booked", "Booked"),
                    ("Cancelled", "Cancelled"),
                    ("Completed", "Completed"),
                    ("Refunded", "Refunded"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tx_hash", models.CharField(max_length=66)),
                ("amount", models.DecimalField(decimal_places=8, max_digits=18)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pharmacy.booking",
                    ),
                ),
            ],
        ),
    ]
