# Generated by Django 5.2.5 on 2025-12-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0008_booking_crypto_amount_booking_tx_hash_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="user_wallet_address",
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
    ]
