# Generated by Django 5.2.5 on 2025-12-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0009_booking_user_wallet_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="user_wallet_address",
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
    ]
