from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views
from pharmacy import views as doc_views
from .views import (
    BloodBankListView,
    BloodBankDetailView,
    BloodBankCreateView,
    BloodBankUpdateView,
)
urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login_view, name='login'),
    path('password-reset/', views.password_reset_request, name='password_reset'),
    path('reset/<uidb64>/<token>/', views.password_reset_confirm, name='password_reset_confirm'),
    path('register/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('doctors/dashboard/', views.doctor_dashboard_view, name='doctor_dashboard'),
    path('my-patients/', views.my_patients, name='my_patients'),
    path('patients/add/', views.add_patient, name='add_patient'),
    path('doctors/', views.doctor_list_view, name='doctor_list'),
    path('doctor/<int:doctor_id>/', views.doctor_detail_view, name='doctor_detail'), 
    path('edit/<int:patient_id>/', views.edit_patient, name='edit_patient'),
    path('delete/<int:patient_id>/', views.delete_patient, name='delete_patient'),
    path('patients/dashboard/', views.patient_dashboard_view, name='patient_dashboard'),
    path('appointments/<int:appointment_id>/details/', views.appointment_detail_view, name='appointment_detail_viwe'),
    path('appointments/', views.doctor_appointment_list, name='doctor_appointment_list'),
    path('doctors/add-appointment/', views.add_appointment, name='add_appointment'),
    path('appointment/edit/<int:appointment_id>/', views.edit_appointment, name='edit_appointment'),
    path('appointment/delete/<int:appointment_id>/', views.delete_appointment, name='delete_appointment'),
    path('appointment/accept/<int:appointment_id>/', views.accept_appointment, name='accept_appointment'),
    path('appointment/cancel/<int:appointment_id>/', views.cancel_appointment, name='cancel_appointment'),
    path('add-patient/', views.add_patient, name='add_patient'),
    path('my_profile/', views.my_profile, name='my_profile'),
    path('add-listing/', views.add_listing, name='add_listing'),
    path('schedule-timing/', views.schedule_timing_view, name='schedule_timing'),
    path('calendar-events/', views.calendar_events, name='calendar_events'),
    path('review/<doctor_id>/', views.doctor_reviews, name='doctor_reviews'),
    path('change-password/', views.change_password, name='change_password'),
    path('profile/', views.profile, name='profile'),
    path('change-password2/', views.change_password2, name='change_password2'),
    path('submit', views.submit_review, name='submit_review'),
    path('book/<int:doctor_id>/', views.book_appointment, name='book_appointment'),
    path('confirm/<int:appointment_id>/', views.confirm_appointment, name='confirm_appointment'),
    path('schedule/time-slot/', views.add_or_edit_time_slot, name='add_time_slot'),
    path('delete-time-slot/<int:slot_id>/', views.delete_time_slot, name='delete_time_slot'),
    path('message/', views.messages_view, name='messages'),
    path('favourite-doctors/', views.favourite_doctors, name='favourite_doctors'),
    path('messages-2/', views.message_dashboard, name='message_dashboard'),
    path('send-message/', views.send_message, name='send_message'),
    path('contact/',views.contact_us,name='contact'),
    path('about/',views.about_us,name='about' ),
    path('clinic/<int:clinic_id>/', views.clinic, name='clinic'),
    path('edit-clinic/', views.edit_clinic, name='edit_clinic'),
    path('clinic/<int:clinic_id>/add-branch/', views.add_branch, name='add_branch'),
    path('branch/<int:branch_id>/edit/', views.edit_branch, name='edit_branch'),
    path('branch/<int:branch_id>/delete/', views.delete_branch, name='delete_branch'),
    path('clinic/<int:clinic_id>/edit-overview/', views.edit_clinic_overview, name='edit_clinic_overview'),
    path('clinic/image/<int:image_id>/delete/', views.delete_gallery_image, name='delete_gallery_image'),
    path('Clinic_list/', views.Clinic_list, name='Clinic_list'),
    path('clinic/<int:clinic_id>/update-contact/', views.update_clinic_contact, name='update_clinic_contact'),
    path('search/', views.search_results, name='search_results'),
    path('clinics/dashboard/', views.clinic_dashboard, name='clinic_dashboard'),
    path('clinics/dashboard/', doc_views.clinic_dashboard, name='clinic_admin_dashboard'),
    path('clinics/appointments/', views.clinic_appointment_list, name='clinic_appointment_list'),
    path('clinics/listings/', views.clinic_listing, name='clinic_listing'),
    path('bloodbanks/', BloodBankListView.as_view(), name='bloodbank-list'),
    path('bloodbanks/<int:pk>/', BloodBankDetailView.as_view(), name='bloodbank-detail'),
    path('bloodbank/create/', BloodBankCreateView.as_view(), name='bloodbank_create'),
    path('dashboard/<int:bank_id>/', views.blood_donation_dashboard, name='blood_donation_dashboard'),
    path('bloodbanks/<int:pk>/edit/', BloodBankUpdateView.as_view(), name='bloodbank-edit'),
    path('inventory/manage/', views.manage_inventory, name='manage_inventory'),
    path('inventory/edit/<int:inventory_id>/', views.edit_inventory, name='edit_inventory'),
    path('requests/new/', views.create_blood_request, name='create_blood_request'),
    path('requests/', views.list_blood_requests, name='blood_requests_list'),
    path('requests/<int:pk>/update-status/', views.update_blood_request_status, name='update_blood_request_status'),
    path('donor/submit/', views.donor_submit_view, name='donor_submit'),
    path('clinic/donors/', views.DonorRecordListView.as_view(), name='admin_donor_list'),
    path('donor/<int:donor_id>/update-status/', views.update_donor_status, name='update_donor_status'),
    path('bloodbank_dashboard',views.bloodbank_dashboard, name='bloodbank_dashboard'),
    path('tests/', views.test_list, name='test_list'),
    path('book/', views.book_tests, name='book_tests'),
    path('add-to-cart/<str:model_name>/<int:object_id>/', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.view_cart, name='view_cart'),
    path('update-cart-item/<int:item_id>/', views.update_cart_item, name='update_cart_item'),
    path('remove-from-cart/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('manage-tests/', views.manage_tests, name='manage_tests'),
    path('edit-test/<int:test_id>/', views.edit_test, name='edit_test'),
    path('add-category/', views.add_category, name='add_category'),
    path('category/update/<int:pk>/', views.update_category, name='update_category'),
    path('category/delete/<int:pk>/', views.delete_category, name='delete_category'),
    path('delete-test/<int:test_id>/', views.delete_test, name='delete_test'),
    path("checkout/", views.checkout_view, name="checkout_view"),
    path("place-order/", views.place_order_view, name="place_order_view"),
    path('booking/success/<int:booking_id>/', views.booking_success_page, name='booking_success_page'),
    path('clinic/bookings/', views.clinic_bookings_view, name='clinic_bookings'),
    path('update-medicine-status/<int:booking_id>/', views.update_medicine_status, name='update_medicine_status'),
    path('clinic/bookings/<int:booking_id>/update/', views.update_booking_status, name='update_booking_status'),
    path('my-bookings/', views.my_bookings_view, name='my_bookings'),
    path("payment-success/",views.payment_success,name="payment_success"),
    path('upload-report/<int:booking_id>/', views.upload_report, name='upload_report'),
    path('delete-report/<int:report_id>/', views.delete_report, name='delete_report'),
    path('edit-report/<int:report_id>/', views.edit_report, name='edit_report'),
    path('cancel-booking/<int:booking_id>/', views.cancel_booking, name='cancel_booking'),
    path('medicineadd-category/', views.add_medicine_category, name='add_medicine_category'),
    path('medicinecategory/update/<int:pk>/', views.update_medicine_category, name='update_medicine_category'),
    path('medicinecategory/delete/<int:pk>/', views.delete_medicine_category, name='delete_medicine_category'),
    path('manage-medicine/', views.manage_medicine, name='manage_medicine'),
    path('update-medicine/<int:pk>/', views.edit_medicine, name='edit_medicine'),
    path('delete-medicine/<int:pk>/', views.delete_medicine, name='delete_medicine'),
    path('medicine/',views.medicine_list,name ='medicine_list'),
    path('medicine/category/<slug:slug>/', views.category_products, name='category_products'),
    path("export/bookings/<str:tab>/<str:filter_type>/csv/", views.export_bookings_csv, name="export_bookings_csv"),
    path("export/bookings/<str:tab>/<str:filter_type>/excel/", views.export_bookings_excel, name="export_bookings_excel"),
    path("video/<int:appointment_id>/", views.video_call, name="video_call"),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
